name: Deploy To SVN

on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Deploy
        run: chmod +x ./deploy.sh && ./deploy.sh
        env:
          SVN_USERNAME: ${{ openedx-woocommerce }}
          SVN_PASSWORD: ${{ CodebullsEdunext*34 }}
